import type { Template } from '@/types'

const rawTemplates: Template[] = [
  {
    id: 30, slug: 'aventis', name: 'Aventis', category: 'Event Management', type: 'Standard',
    bg: '#0b0b12', accent: '#0b0b12', dark: true, tagBg: '#1c1830', tagColor: '#b0a0e0',
    image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F49787%2Faventis-QYYJL4x0l0nKMoweONPgxxWhSM3QW3&w=1200&q=90',
    image2: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F49787%2Faventis-VQoYhvcjjhtAIdYAPoFPAlSTQgS2L0&w=1200&q=90',
    description: 'A bold conference and virtual-event site with speakers, agenda and ticketing built in.',
    about: 'Aventis is built for teams running conferences, summits and virtual events. Speaker profiles, a day-by-day agenda, tiered ticket pricing and a contact flow are all ready to go — just drop in your own event details.',
    features: ['Speaker & organiser profile grids', 'Multi-day agenda / schedule sections', 'Tiered ticket pricing blocks', 'Dark, high-contrast event styling', 'Testimonials and FAQ sections', 'Fully responsive layout'],
    pages: ['Home', 'About Us', 'Organisers / Agenda', 'Speakers', 'Pricing', 'Contact'],
    tags: ['Event Management', 'Dark', 'Conference', 'Ticketing'],
    views: 13400,
    previewUrl: 'https://aventis.webclawd.in/',
  },
  {
    id: 31, slug: 'eventry', name: 'Eventry', category: 'Event Management', type: 'Standard',
    bg: '#f7f7f5', accent: '#f7f7f5', dark: false, tagBg: '#e4e0f8', tagColor: '#5030a0',
    image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F59376%2Feventry-wcxpv9WQmDCgfqDVaiFJoh2RwePsyj&w=1200&q=90',
    image2: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F59376%2Feventry-988AupL4EE8vBixfL6pPkKCEsTyjYj&w=1200&q=90',
    description: 'An events and festivals platform with listings, speaker highlights and a booking form.',
    about: 'Eventry is built for event organisers running conferences, festivals and community meetups. Upcoming and past events, attendee testimonials, simple pricing plans and a full booking form come ready-made so you can launch fast.',
    features: ['Upcoming & recent event listings', 'Attendee testimonial carousel', 'Simple tiered pricing plans', 'Event booking / enquiry form', 'Blog / articles section', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Events', 'Event Details', 'Blog', 'Contact'],
    tags: ['Event Management', 'Light', 'Festival', 'Booking'],
    views: 9800,
    previewUrl: 'https://eventry.webclawd.in/',
  },
  {
    id: 32, slug: 'oralcare', name: 'Oralcare', category: 'Healthcare', type: 'Standard',
    bg: '#f6f2ec', accent: '#f6f2ec', dark: false, tagBg: '#e8ded0', tagColor: '#7a5830',
    image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F59281%2Foral-care-N4lH95jSFjrdOBxj1nmFTjfKrL3xd5&w=1200&q=90',
    image2: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F59281%2Foral-care-dIxY7eSsaQt2wQQcgJ9mkeeu0Rzubz&w=1200&q=90',
    description: 'A warm, patient-friendly dental clinic site with services, team and online booking.',
    about: 'Oralcare gives a dental practice a calm, trustworthy online presence. Service breakdowns, a before/after gallery, team profiles and an appointment-booking form are all included so patients can find and book care easily.',
    features: ['Service breakdown cards', 'Before & after smile gallery', 'Dentist / team profile section', 'Appointment booking form', 'Patient testimonials', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Services', 'Team', 'Blog', 'Book Appointment'],
    tags: ['Healthcare', 'Light', 'Dental', 'Booking'],
    views: 8600,
    previewUrl: 'https://oralcare.webclawd.in/',
  },
  {
    id: 33, slug: 'dentora', name: 'Dentora', category: 'Healthcare', type: 'Standard',
    bg: '#ffffff', accent: '#ffffff', dark: false, tagBg: '#dceaf5', tagColor: '#1a5a8a',
    image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F60124%2Fdentora-cptaOCm5DsUHOw3tiXd4gwytak7eiv&w=1200&q=90',
    image2: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F60124%2Fdentora-cptaOCm5DsUHOw3tiXd4gwytak7eiv&w=1200&q=90',
    description: 'A premium, trust-building website for dental and medical clinics with case studies.',
    about: 'Dentora is a comprehensive site for dental and medical clinics that want to build patient trust from the first visit. Treatment breakdowns, real patient case studies with before/after results, and a full blog give the practice a premium, credible presence.',
    features: ['Ten-plus treatment/service tiles', 'Patient case studies with results', 'Google-review style social proof', 'Insights & dental-care blog', 'Multiple homepage hero variations', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Services', 'Case Studies', 'Blog', 'Contact'],
    tags: ['Healthcare', 'Light', 'Dental', 'Premium'],
    views: 11200,
    previewUrl: 'https://dentora.webclawd.in/',
  },
  {
    id: 34, slug: 'dentiva', name: 'Dentiva', category: 'Healthcare', type: 'Standard',
    bg: '#fbfaf8', accent: '#fbfaf8', dark: false, tagBg: '#eee6dc', tagColor: '#8a6a40',
    image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F54136%2Fdeentiva-RZSuWBwDoWaQ53r4G15adZP4gLTu3A&w=1200&q=90',
    image2: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F54136%2Fdeentiva-Rpaa87idTifSQT8ufERqsHI989BLXO&w=1200&q=90',
    description: 'A clean, minimal 13-page dental clinic template built to put anxious patients at ease.',
    about: 'Dentiva pairs a sleek, minimal layout with treatment pricing, before/after results and flexible scheduling to turn nervous visitors into confident patients. A full 13-page structure covers everything a growing clinic needs.',
    features: ['Treatment cards with pricing & duration', 'Before/after results slider', 'Flexible scheduling section', 'Patient testimonial blocks', 'Doctor profile pages', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Service', 'Doctor', 'Reviews', 'Book Appointment'],
    tags: ['Healthcare', 'Light', 'Dental', 'Minimal'],
    views: 7400,
    previewUrl: 'https://dentiva.webclawd.in/',
  },
  {
    id: 35, slug: 'fitcore', name: 'Fitcore', category: 'Fitness', type: 'Standard',
    bg: '#111111', accent: '#111111', dark: true, tagBg: '#dcebd0', tagColor: '#3a6b28',
    image: 'https://framerusercontent.com/images/lWa9KWj1U09h2wy4Fxavysh7uA.jpg?width=5192&height=3466',
    image2: 'https://framerusercontent.com/images/SGmk37b8TDX43mcsVuBwFTVon0Y.jpg?width=5200&height=4160',
    description: 'A bold gym and fitness studio site with classes, trainers and membership pricing.',
    about: 'Fitcore gives a gym or fitness studio a high-energy online presence. Class listings, trainer profiles, tiered membership pricing and a testimonial carousel come ready-made so members can find the right plan and book in seconds.',
    features: ['Class listing grid', 'Tiered membership pricing', 'Trainer profile section', 'Testimonial carousel', 'Assess → Train → Evolve process section', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Classes', 'Contact'],
    tags: ['Fitness', 'Gym', 'Dark', 'Classes'],
    views: 6200,
    previewUrl: 'https://fitcore.webclawd.in/',
  },
  {
    id: 36, slug: 'fitbix', name: 'Fitbix', category: 'Fitness', type: 'Standard',
    bg: '#0d0d0d', accent: '#0d0d0d', dark: true, tagBg: '#dcebd0', tagColor: '#3a6b28',
    image: 'https://framerusercontent.com/images/ROVOrmX1rG1spKS74lHIdXLPO4.png',
    image2: 'https://framerusercontent.com/images/tK6XOpGXE3FOnqaJtjrXivJT5TA.png?width=3144&height=1884',
    description: 'A modern gym and personal-trainer site built to showcase services and boost conversions.',
    about: 'Fitbix is built for gyms and personal trainers who want a clean, conversion-focused online presence. Service breakdowns, a training team grid, before/after transformation shots, flexible pricing plans and a full FAQ and blog come ready to launch.',
    features: ['Service detail pages', 'Trainer team grid', 'Before/after transformation section', 'Monthly & yearly pricing plans', 'FAQ and blog sections', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Services', 'Pricing', 'Team', 'Blog', 'FAQ', 'Contact'],
    tags: ['Fitness', 'Gym', 'Dark', 'Personal Training'],
    views: 5400,
    previewUrl: 'https://fitbix.webclawd.in/',
  },
  {
    id: 37, slug: 'fit-zone', name: 'Fitzone', category: 'Fitness', type: 'Standard',
    bg: '#111111', accent: '#111111', dark: true, tagBg: '#dcebd0', tagColor: '#3a6b28',
    image: 'https://framerusercontent.com/images/YuVoTTFzcCKi4OZP5Q2zyyUF8.png',
    image2: 'https://framerusercontent.com/images/iHtENhuQaWhq99BdIn5lyZtsQM.jpeg?width=4898&height=3265',
    description: 'A conversion-focused gym and fitness studio site with classes, trainers and membership tiers.',
    about: 'Fitzone is a clean, conversion-focused template for gyms, fitness studios and personal trainers. Class categories, a trainer showcase, day/month/year membership passes and a fitness blog give visitors everything they need to sign up.',
    features: ['Class category showcase', 'Trainer team grid', 'Day/month/year membership passes', 'FAQ accordion', 'Fitness blog section', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Classes', 'Pricing', 'Blog', 'Contact'],
    tags: ['Fitness', 'Gym', 'Dark', 'Membership'],
    views: 4800,
    previewUrl: 'https://fit-zone.webclawd.in/',
  },
  {
    id: 38, slug: 'lumina', name: 'Lumina', category: 'Yoga', type: 'Standard',
    bg: '#f5f0e8', accent: '#f5f0e8', dark: false, tagBg: '#e8ecd8', tagColor: '#5a6b28',
    image: 'https://framerusercontent.com/images/AbFwcTWxz6L9EV2upoyJCx5fty8.jpg?width=2528&height=1696',
    image2: 'https://framerusercontent.com/images/fP5oIEfiBhQqpOxdQ1SG900kks8.jpg?width=1848&height=1056',
    description: 'A calm, minimalist yoga studio site with classes, teacher profiles and a blog.',
    about: 'Lumina brings a quiet, boutique-studio feel online. Class listings, a teacher roster, a workshop-driven blog and a full FAQ let visitors find their practice and book without friction, all wrapped in a soft, editorial visual style.',
    features: ['Class listing with detail pages', 'Teacher profile grid', 'Timetable & pricing pages', 'Workshop-driven blog', 'Testimonial section', 'Fully responsive layout'],
    pages: ['Home', 'Classes', 'Pricing', 'Teachers', 'Blog', 'Timetable', 'Contact'],
    tags: ['Yoga', 'Wellness', 'Light', 'Studio'],
    views: 3900,
    previewUrl: 'https://lumina.webclawd.in/',
  },
  {
    id: 39, slug: 'yogastic', name: 'Yogastic', category: 'Yoga', type: 'Standard',
    bg: '#f7f3ec', accent: '#f7f3ec', dark: false, tagBg: '#e8ecd8', tagColor: '#5a6b28',
    image: 'https://framerusercontent.com/images/d8EzzvPjidO2aMyLGd3YX8sDY.jpg?width=2732&height=1600',
    image2: 'https://framerusercontent.com/images/yeqDn3pzzDmOESObz8mPxd5my2c.jpg?width=2580&height=1452',
    description: 'A full-featured yoga studio site with class booking, a retreat page and a built-in shop.',
    about: 'Yogastic is built for studios that want to do more than showcase classes — it includes a live class-booking table, a yoga-retreat spotlight section, an e-commerce-ready product shop for mats and accessories, and a three-version blog and contact system.',
    features: ['Live class booking table', 'Retreat spotlight section', 'Built-in product shop', 'Instructor profiles', 'Multi-version blog & contact pages', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Classes', 'Shop', 'Retreat', 'Instructors', 'Blog', 'Contact'],
    tags: ['Yoga', 'Wellness', 'Light', 'Shop'],
    views: 5100,
    previewUrl: 'https://yogastic.webclawd.in/',
  },
  {
    id: 40, slug: 'pranava', name: 'Pranava', category: 'Yoga', type: 'Standard',
    bg: '#111111', accent: '#111111', dark: true, tagBg: '#e8ecd8', tagColor: '#5a6b28',
    image: 'https://framerusercontent.com/images/wznNQNTCRcO9HbO6HPrXlUhMjEo.png',
    image2: 'https://framerusercontent.com/images/YEzfzmRLUO5nZZfjj1fBec7QiV0.png?width=1672&height=968',
    description: 'A dark, editorial yoga and wellness site with class carousels and a video hero.',
    about: 'Pranava pairs a moody, editorial dark theme with a video hero and a swipeable class carousel, giving a yoga or wellness brand a premium, high-production feel. Detailed class pages, a testimonial carousel and a rich FAQ round out the booking journey.',
    features: ['Video hero section', 'Swipeable class carousel', 'Individual class detail pages', 'Testimonial carousel', 'FAQ accordion', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Classes', 'Blog', 'Contact'],
    tags: ['Yoga', 'Wellness', 'Dark', 'Editorial'],
    views: 3400,
    previewUrl: 'https://pranava.webclawd.in/',
  },
  {
    id: 41, slug: 'aurivio', name: 'Aurivio', category: 'Interior Design', type: 'Standard',
    bg: '#111111', accent: '#111111', dark: true, tagBg: '#f0e4d8', tagColor: '#8a5a2a',
    image: 'https://framerusercontent.com/images/D4UiuOv9cRvU8s9znKN8L1Vt0r4.png',
    image2: 'https://framerusercontent.com/images/9t4Zigf9523mJYp95ZIcl6FmvSU.png?width=800&height=1200',
    description: 'A dark, editorial interior design studio site with a portfolio and client stats.',
    about: 'Aurivio gives an interior design studio a bold, magazine-style presence. A six-service breakdown, a portfolio of completed residential projects, client-stat counters and a full FAQ walk visitors from first impression to booked consultation.',
    features: ['Six-service breakdown grid', 'Portfolio with project detail pages', 'Client stats counter section', 'FAQ accordion', 'Location & contact section', 'Fully responsive layout'],
    pages: ['Home', 'Services', 'Portfolio', 'Contact Us'],
    tags: ['Interior Design', 'Dark', 'Portfolio', 'Editorial'],
    views: 4100,
    previewUrl: 'https://aurivio.webclawd.in/',
  },
  {
    id: 42, slug: 'intro', name: 'Intro', category: 'Interior Design', type: 'Standard',
    bg: '#f7f4ee', accent: '#f7f4ee', dark: false, tagBg: '#f0e4d8', tagColor: '#8a5a2a',
    image: 'https://framerusercontent.com/images/3emHBWPSNflEa9T7eGxuPmBvZaw.png',
    image2: 'https://framerusercontent.com/images/HoFSmQLVAbowOLkI3TfmPKLqdIw.png',
    description: 'A light, elegant interior & architecture studio site with services, projects and a blog.',
    about: 'Intro is built for interior design and architecture studios that want a warm, editorial feel. A three-step design process, a rotating testimonial carousel, a full project gallery and a blog give visitors everything they need before reaching out.',
    features: ['Service detail pages', '3-step design process section', 'Testimonial carousel', 'Project gallery with detail pages', 'Blog section', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Services', 'Projects', 'Blog', 'Contact'],
    tags: ['Interior Design', 'Light', 'Portfolio', 'Blog'],
    views: 3700,
    previewUrl: 'https://intro.webclawd.in/',
  },
  {
    id: 43, slug: 'pearlgem', name: 'PearlGem', category: 'Jewellery', type: 'Ecommerce',
    bg: '#f5efe6', accent: '#f5efe6', dark: false, tagBg: '#f0e0d0', tagColor: '#8a6a2a',
    image: 'https://framerusercontent.com/images/ow3uE9XJz8ZW6MdQC5IWUGjeQYY.png?width=1300&height=780',
    image2: 'https://framerusercontent.com/images/fkW7mHqVOLfpbZFTh5Bsgmcb7Q.png?width=1300&height=700',
    description: 'A full jewellery ecommerce storefront with shop-by-category, shop-by-shape and a product catalogue.',
    about: 'PearlGem is a complete online jewellery store, not just a showcase page. Shop-by-category and shop-by-shape browsing, a bestseller product grid, individual product detail pages and a newsletter signup give a jewellery brand everything it needs to sell online.',
    features: ['Shop by category (rings, earrings, necklaces...)', 'Shop by shape browsing', 'Product listing & detail pages', 'Bestseller & popular product grids', 'Testimonials section', 'Fully responsive layout'],
    pages: ['Home', 'Product Listing', 'Product Detail', 'About Us', 'Contact Us'],
    tags: ['Jewellery', 'Ecommerce', 'Light', 'Shop'],
    views: 4600,
    previewUrl: 'https://pearlgem.webclawd.in/',
  },
  {
    id: 44, slug: 'estelle', name: 'Estelle', category: 'Jewellery', type: 'Ecommerce',
    bg: '#f7f4ef', accent: '#f7f4ef', dark: false, tagBg: '#f0e0d0', tagColor: '#8a6a2a',
    image: 'https://framerusercontent.com/images/z6DBKPpYoEd0B4vfeOx9768991k.jpg',
    image2: 'https://framerusercontent.com/images/gPRaTunYm8woOct9QsTbOWHdc.png?width=2688&height=1792',
    description: 'A premium, editorial jewellery ecommerce template with collection pages and a luxury feel.',
    about: 'Estelle is a premium, editorial-style storefront for luxury jewellery brands. Dedicated collection pages for necklaces, bracelets, earrings and rings, an elegant product-card layout and a newsletter section create a boutique, high-end shopping experience.',
    features: ['Dedicated collection pages per category', 'Editorial hero & product cards', 'Product detail pages', 'Newsletter signup section', 'FAQ page', 'Fully responsive layout'],
    pages: ['Home', 'Collection', 'Product Detail', 'FAQs', 'Contact'],
    tags: ['Jewellery', 'Ecommerce', 'Light', 'Editorial'],
    views: 5300,
    previewUrl: 'https://estelle.webclawd.in/',
  },
  {
    id: 45, slug: 'salonix', name: 'Salonix', category: 'Salon & Beauty', type: 'Standard',
    bg: '#111111', accent: '#111111', dark: true, tagBg: '#f8e0e8', tagColor: '#8a2a5a',
    image: 'https://framerusercontent.com/images/TdST9JIIzVvXQAAXYyTH9dFVrR8.png',
    image2: 'https://framerusercontent.com/images/EICbiBGjWoxqYIkuS2LukwjiUQ.png?width=1728&height=1056',
    description: 'A premium hair & beauty salon site with online booking and a six-service showcase.',
    about: 'Salonix gives a hair & beauty salon a premium, editorial presence. A problem-to-solution section, six signature services with price ranges, a three-step process and a full booking form let clients go from browsing to booked in one visit.',
    features: ['Online booking form', 'Six-service showcase with pricing', 'Problem → solution section', 'Testimonial carousel', 'FAQ accordion', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Services', 'Contact'],
    tags: ['Salon', 'Beauty', 'Dark', 'Booking'],
    views: 4400,
    previewUrl: 'https://salonix.webclawd.in/',
  },
  {
    id: 46, slug: 'salona', name: 'Salona', category: 'Salon & Beauty', type: 'Standard',
    bg: '#f7f4ee', accent: '#f7f4ee', dark: false, tagBg: '#f8e0e8', tagColor: '#8a2a5a',
    image: 'https://framerusercontent.com/images/SYXWqBVBMTjy0l4tWsPAtzdlxg.png',
    image2: 'https://framerusercontent.com/images/YfxWKL5tzyQWvvBtvOqiEGu2yA.jpg?width=4096&height=2731',
    description: 'A modern salon & barbershop site with a team roster, blog and calendar booking.',
    about: 'Salona is built for modern salons, spas and barbershops. A luxury service showcase, a full team/stylist roster with profile pages, a blog for salon tips and insights, and Google/Apple calendar booking links make it a complete, ready-to-launch package.',
    features: ['Service showcase with detail pages', 'Team/stylist roster with profile pages', 'Blog & insights section', 'Google & Apple Calendar booking', 'Testimonial carousel', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Services', 'Team', 'Gallery', 'Blog', 'FAQ', 'Reviews', 'Pricing', 'Contact'],
    tags: ['Salon', 'Beauty', 'Light', 'Booking'],
    views: 3800,
    previewUrl: 'https://salona.webclawd.in/',
  },
  {
    id: 47, slug: 'craving', name: 'Craving', category: 'Cloud Kitchen', type: 'Ecommerce',
    bg: '#f7f3ec', accent: '#f7f3ec', dark: false, tagBg: '#f8e4d0', tagColor: '#8a4a2a',
    image: 'https://framerusercontent.com/images/sARtldtqxPg7kQaHT7CxHZ1k34.png',
    image2: 'https://framerusercontent.com/images/kSOYRO6Ny1CiDGMj8PvuhIZcJNA.png',
    description: 'A sleek restaurant & cafe site with a filterable menu, gallery and food blog.',
    about: 'Craving is built for restaurants, cafes and cloud kitchens that want to show off their menu in style. A filterable veg/non-veg/drinks menu with individual dish pages, a food gallery, customer reviews and a foodie blog cover the full guest journey from browsing to booking a table.',
    features: ['Filterable menu (Veg / Non-Veg / Drinks)', 'Individual dish detail pages', 'Food gallery grid', 'Customer review carousel', 'Foodie blog section', 'Fully responsive layout'],
    pages: ['Home', 'About', 'Menu', 'Blog', 'Contact'],
    tags: ['Cloud Kitchen', 'Restaurant', 'Light', 'Menu'],
    views: 4200,
    previewUrl: 'https://craving.webclawd.in/',
  },
  {
    id: 48, slug: 'aroma', name: 'Aromas Kitchen', category: 'Cloud Kitchen', type: 'Ecommerce',
    bg: '#faf6ee', accent: '#faf6ee', dark: false, tagBg: '#f8e4d0', tagColor: '#8a4a2a',
    image: 'https://images.unsplash.com/photo-1742281257687-092746ad6021?fm=jpg&q=80&w=1200&auto=format&fit=crop',
    image2: 'https://images.unsplash.com/photo-1742281257707-0c7f7e5ca9c6?fm=jpg&q=80&w=900&auto=format&fit=crop',
    description: 'A home-cooked meal subscription site with a live price calculator and daily rotating menus.',
    about: 'Aromas Kitchen is a full subscription-meal ordering experience, not just a menu page. An interactive price calculator builds a custom plan in real time, a daily-rotating menu shows exactly what\u2019s being cooked, and a neighbourhood-by-zone delivery checker covers 25+ areas across the city.',
    features: ['Interactive price calculator', 'Daily rotating menu & full weekly rotation', 'Delivery-area checker by zone', 'Tiered subscription plans (Starter/Standard/Premium)', 'Photo gallery & subscriber reviews', 'Fully responsive layout'],
    pages: ['Home', 'Subscriptions', 'Menu', 'Services', 'About', 'Gallery', 'Reviews', 'FAQ', 'Contact'],
    tags: ['Cloud Kitchen', 'Subscription', 'Light', 'Calculator'],
    views: 3100,
    previewUrl: 'https://aroma.webclawd.in/',
  },
  {
    id: 49, slug: 'ecom', name: 'Ecom', category: 'Fashion', type: 'Ecommerce',
    bg: '#0f0f0f', accent: '#0f0f0f', dark: true, tagBg: '#eae6e0', tagColor: '#3a3a3a',
    image: 'https://image.thum.io/get/width/1200/crop/900/https://ecom.webclawd.in/',
    image2: 'https://image.thum.io/get/width/1200/crop/900/https://ecom.webclawd.in/',
    description: 'A bold streetwear & apparel storefront with animated hero text and full shop flow.',
    about: 'Ecom is a high-energy fashion storefront built for streetwear and apparel brands. A kinetic-type hero, category shopping by men/women/kids, a seasonal drop showcase and a full journal keep the store feeling alive from the first scroll.',
    features: ['Animated kinetic-text hero', 'Shop by category (Men/Women/Kids)', 'Seasonal drop showcase', 'Filterable best-sellers grid', 'Style journal / blog section', 'Fully responsive layout'],
    pages: ['Home', 'Shop', 'Journal', 'About', 'FAQ', 'Contact'],
    tags: ['Fashion', 'Boutique', 'Dark', 'Ecommerce'],
    views: 2600,
    previewUrl: 'https://ecom.webclawd.in/',
  },
  {
    id: 50, slug: 'moss', name: 'Moss & Stone', category: 'Fashion', type: 'Ecommerce',
    bg: '#f4f1ea', accent: '#f4f1ea', dark: false, tagBg: '#e4e0d4', tagColor: '#5a5240',
    image: 'https://framerusercontent.com/assets/KIXZhSMTMStslWL43dRf7IQo0.png',
    image2: 'https://image.thum.io/get/width/1200/crop/900/https://moss.webclawd.in/',
    description: 'An earth-toned, slow-fashion boutique site with sustainability metrics and product pages.',
    about: 'Moss & Stone is a quiet-luxury boutique template for sustainable, slow-fashion brands. Earth-toned product photography, category shopping by tees/bottoms/outerwear/headwear, a sustainability metrics section and full product detail pages give the store an editorial, trust-building feel.',
    features: ['Earth-toned editorial hero with video', 'Shop by category grid', 'Bestsellers & product detail pages', 'Sustainability / conscious-calculations section', 'Customer testimonial section', 'Fully responsive layout'],
    pages: ['Home', 'Shop', 'New Arrivals', 'Product Detail', 'About', 'Size Guide', 'Contact'],
    tags: ['Fashion', 'Boutique', 'Light', 'Sustainable'],
    views: 2100,
    previewUrl: 'https://moss.webclawd.in/',
  },

  // ── Designer portfolio templates ──
  {
    id: 51, slug: 'inertia', name: 'Inertia', category: 'Portfolio', type: 'Portfolio',
    bg: '#0a0a0f', accent: '#0a0a0f', dark: true, tagBg: '#1a1830', tagColor: '#a090d0',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://inertia.webclawd.in/',
    description: 'Inertia — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Inertia is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Inertia'],
    views: 1200,
    previewUrl: 'https://inertia.webclawd.in/',
  },
  {
    id: 52, slug: 'jores', name: 'Jores', category: 'Portfolio', type: 'Portfolio',
    bg: '#fbfaf8', accent: '#fbfaf8', dark: false, tagBg: '#eee6dc', tagColor: '#8a6a40',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://jores.webclawd.in/',
    description: 'Jores — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Jores is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Jores'],
    views: 1540,
    previewUrl: 'https://jores.webclawd.in/',
  },
  {
    id: 53, slug: 'struqx', name: 'Struqx', category: 'Portfolio', type: 'Portfolio',
    bg: '#0a0a0f', accent: '#0a0a0f', dark: true, tagBg: '#1a1830', tagColor: '#a090d0',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://struqx.webclawd.in/',
    description: 'Struqx — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Struqx is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Struqx'],
    views: 1880,
    previewUrl: 'https://struqx.webclawd.in/',
  },
  {
    id: 54, slug: 'vertora', name: 'Vertora', category: 'Portfolio', type: 'Portfolio',
    bg: '#fbfaf8', accent: '#fbfaf8', dark: false, tagBg: '#eee6dc', tagColor: '#8a6a40',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://vertora.webclawd.in/',
    description: 'Vertora — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Vertora is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Vertora'],
    views: 2220,
    previewUrl: 'https://vertora.webclawd.in/',
  },
  {
    id: 55, slug: 'visenro', name: 'Visenro', category: 'Portfolio', type: 'Portfolio',
    bg: '#0a0a0f', accent: '#0a0a0f', dark: true, tagBg: '#1a1830', tagColor: '#a090d0',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://visenro.webclawd.in/',
    description: 'Visenro — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Visenro is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Visenro'],
    views: 2560,
    previewUrl: 'https://visenro.webclawd.in/',
  },
  {
    id: 56, slug: 'xenith', name: 'Xenith', category: 'Portfolio', type: 'Portfolio',
    bg: '#fbfaf8', accent: '#fbfaf8', dark: false, tagBg: '#eee6dc', tagColor: '#8a6a40',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://xenith.webclawd.in/',
    description: 'Xenith — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Xenith is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Xenith'],
    views: 2900,
    previewUrl: 'https://xenith.webclawd.in/',
  },
  {
    id: 57, slug: 'adox', name: 'Adox', category: 'Portfolio', type: 'Portfolio',
    bg: '#0a0a0f', accent: '#0a0a0f', dark: true, tagBg: '#1a1830', tagColor: '#a090d0',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://adox.webclawd.in/',
    description: 'Adox — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Adox is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Adox'],
    views: 3240,
    previewUrl: 'https://adox.webclawd.in/',
  },
  {
    id: 58, slug: 'apnar', name: 'Apnar', category: 'Portfolio', type: 'Portfolio',
    bg: '#fbfaf8', accent: '#fbfaf8', dark: false, tagBg: '#eee6dc', tagColor: '#8a6a40',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://apnar.webclawd.in/',
    description: 'Apnar — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Apnar is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Apnar'],
    views: 3580,
    previewUrl: 'https://apnar.webclawd.in/',
  },
  {
    id: 59, slug: 'axjero', name: 'Axjero', category: 'Portfolio', type: 'Portfolio',
    bg: '#0a0a0f', accent: '#0a0a0f', dark: true, tagBg: '#1a1830', tagColor: '#a090d0',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://axjero.webclawd.in/',
    description: 'Axjero — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Axjero is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Axjero'],
    views: 3920,
    previewUrl: 'https://axjero.webclawd.in/',
  },
  {
    id: 60, slug: 'bungee', name: 'Bungee', category: 'Portfolio', type: 'Portfolio',
    bg: '#fbfaf8', accent: '#fbfaf8', dark: false, tagBg: '#eee6dc', tagColor: '#8a6a40',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://bungee.webclawd.in/',
    description: 'Bungee — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Bungee is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Bungee'],
    views: 4260,
    previewUrl: 'https://bungee.webclawd.in/',
  },
  {
    id: 61, slug: 'fluinto', name: 'Fluinto', category: 'Portfolio', type: 'Portfolio',
    bg: '#0a0a0f', accent: '#0a0a0f', dark: true, tagBg: '#1a1830', tagColor: '#a090d0',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://fluinto.webclawd.in/',
    description: 'Fluinto — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Fluinto is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Fluinto'],
    views: 4600,
    previewUrl: 'https://fluinto.webclawd.in/',
  },
  {
    id: 62, slug: 'glowix', name: 'Glowix', category: 'Portfolio', type: 'Portfolio',
    bg: '#fbfaf8', accent: '#fbfaf8', dark: false, tagBg: '#eee6dc', tagColor: '#8a6a40',
    image: 'https://image.thum.io/get/width/1200/crop/900/noanimate/https://glowix.webclawd.in/',
    description: 'Glowix — a premium designer portfolio template for product, UX, and visual designers.',
    about: 'Glowix is a hand-crafted portfolio template built to help designers present case studies with clarity and polish. Fully responsive, fast-loading, and ready to customise with your own work.',
    features: ['Case study layout built for storytelling', 'Fully responsive across devices', 'Fast-loading, SEO-friendly pages', 'Easy content updates, no code required', 'Custom domain + hosting', 'Live in 48 hours'],
    pages: ['Home', 'Case Studies', 'About', 'Contact'],
    tags: ['Portfolio', 'Designer', 'Glowix'],
    views: 4940,
    previewUrl: 'https://glowix.webclawd.in/',
  },
]

export const templates: Template[] = rawTemplates.map(t => {
  if (t.previewUrl) {
    // Templates that already ship a real external screenshot (e.g. from the
    // source marketplace) keep that image instead of being forced onto the
    // local `/${slug}-screenshot.png` convention.
    if (t.image && t.image.startsWith('http')) {
      return t
    }
    return {
      ...t,
      image: `/${t.slug}-screenshot.png`
    }
  }
  return t
})
